### ISSUE TITLE
Rails 6 deprecation warning

### ISSUE THREAD

**Issue by asgerb** [Sign2Pay/mongoid-archivable#16]
I'm getting a deprecation warning when running Rails 6.0:

```
DEPRECATION WARNING: `Module#parent` has been renamed to `module_parent`. `parent` is deprecated and will be removed in Rails 6.1.
```

I believe it's is stemming from `Mongoid::Archivable::Depot`: https://github.com/Sign2Pay/mongoid-archivable/blob/f05c53be283782c540c77e81748cdb25f41e10ac/lib/mongoid/archivable/depot.rb#L11

I'd love to submit a PR with a fix, but I'm unsure how best to go about it... I could simply replace `parent` with `module_parent`, but I'm quite certain it would break backwards compatibility.

I guess we would need to check for which version of `ActiveSupport` is used? Curious what your thoughts are 🙂

**Comment by tomasc** [comment]
@asgerb feel free to submit PR. I guess you can do it depending on Rails version or based on result of `respond_to?(…)`.
Thanks!
T
