### ISSUE TITLE
Release 1.4.2

### ISSUE THREAD

**Issue by tomasc** [Sign2Pay/mongoid-archivable#8]
@tilsammans I made a small adjustment to the code (#7 memoization of the original document) and merged it to master. Could you please update the version to `1.4.2` and release this version of the gem? Thanks!

**Comment by tomasc** [comment]
@nicklloyd @nicolasmertens @tilsammans any chance to release new version of the gem with this small update?

**Comment by tilsammans** [comment]
You're right, it slipped my mind. I'll release this weekend.

**Comment by tomasc** [comment]
wonderful, thanks a lot!
